name: Linux

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Apt Update
      run: sudo apt-get update
    - name: Apt Install
      run: sudo apt-get install libasound2-dev libxinerama-dev libgl1-mesa-dev libxi-dev --yes --quiet
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Get Kinc
      run: git clone --recursive https://github.com/Kode/Kinc.git
    - name: Compile
      run: ./Kinc/make --compile
    - name: Get krafix_bin
      run: git clone https://github.com/Kode/krafix_bin.git
    - name: Copy binary
      run: cp build/Release/krafix krafix_bin/krafix-linux64
    - name: Set name
      run: git config --global user.name "Robbot"
    - name: Set email
      run: git config --global user.email "robbot2019@robdangero.us"
    - name: Commit binary
      id: commit
      continue-on-error: true
      run: git -C krafix_bin commit -a -m "Update Linux binary to $GITHUB_SHA."
    - name: Tag binary
      if: steps.commit.outcome == 'success'
      run: git -C krafix_bin tag linux_$GITHUB_SHA
    - name: Push binary
      id: push1
      if: steps.commit.outcome == 'success'
      continue-on-error: true
      run: git -C krafix_bin push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/krafix_bin.git main --tags
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}
    - name: Pull
      if: steps.commit.outcome == 'success' && steps.push1.outcome != 'success'
      run: git -C krafix_bin pull
    - name: Push binary again
      if: steps.commit.outcome == 'success' && steps.push1.outcome != 'success'
      continue-on-error: true
      run: git -C krafix_bin push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/krafix_bin.git main --tags
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}
